<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sliderButtonDisplayNonWorkingDays</name>
   <tag></tag>
   <elementGuidId>ea36a6d1-375b-4e07-a619-d88381516b42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider round</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/section[@class=&quot;wrapper-container&quot;]/main[@class=&quot;main-content&quot;]/global[1]/section[1]/div[@class=&quot;global-component&quot;]/div[@class=&quot;settings row&quot;]/div[@class=&quot;col-sm-6 desktop&quot;]/div[@class=&quot;desk-setting-panel row&quot;]/div[@class=&quot;col-sm-6 setting-value&quot;]/div[@class=&quot;sliding&quot;]/label[@class=&quot;switch&quot;]/span[@class=&quot;slider round&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/span</value>
   </webElementXpaths>
</WebElementEntity>
